# Generated by Django 2.2.5 on 2019-11-08 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cleaness',
            new_name='cleanliness',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='place',
            new_name='location',
        ),
    ]
